databases:
  - name: nupsdb
    plan: free
    databaseName: nupsdb
    user: nupsUser

services:
  - type: web
    plan: free
    name: nupsApi
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn nups.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nupsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4